name: PennLFG CI

on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-test-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 21
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - run: npm install
      - run: npm test
      - run: npm run lint
      - run: npm run build --if-present